// GT Lead Log import — Phase 1 canonical error/warning codes (Part 13/14).
// Messages are deliberately short and safe: no notes content, no buyer/
// seller names extracted from notes — see src/lib/leadImport/validate.ts.

// ── Source-level fatal (the whole Preview cannot classify any row) ─────────
export const SOURCE_FATAL = {
  MISSING_HEADERS: 'MISSING_HEADERS',
  DUPLICATE_HEADERS: 'DUPLICATE_HEADERS',
  DUPLICATE_LEAD_ID: 'DUPLICATE_LEAD_ID',
  SPREADSHEET_NOT_ACCESSIBLE: 'SPREADSHEET_NOT_ACCESSIBLE',
  SHEET_NOT_FOUND: 'SHEET_NOT_FOUND',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  GOOGLE_API_ERROR: 'GOOGLE_API_ERROR',
  GOOGLE_CREDENTIALS_MISSING: 'GOOGLE_CREDENTIALS_MISSING',
} as const;

// ── Source-level warning (non-fatal) ────────────────────────────────────────
export const SOURCE_WARNING = {
  EXTRA_COLUMNS: 'EXTRA_COLUMNS',
} as const;

// ── Row-level ────────────────────────────────────────────────────────────
export const ROW_ISSUE = {
  MISSING_LEAD_ID: 'MISSING_LEAD_ID',
  INVALID_LEAD_ID: 'INVALID_LEAD_ID',
  MISSING_UPDATED_AT: 'MISSING_UPDATED_AT',
  INVALID_UPDATED_AT: 'INVALID_UPDATED_AT',
  MISSING_ITEM_ID: 'MISSING_ITEM_ID',
  INVALID_ITEM_ID: 'INVALID_ITEM_ID',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_NOT_OWNED_BY_SOURCE_USER: 'ITEM_NOT_OWNED_BY_SOURCE_USER',
  ITEM_MISMATCH_WITH_EXISTING_LEAD: 'ITEM_MISMATCH_WITH_EXISTING_LEAD',
  INVALID_FIRST_CONTACT_DATE: 'INVALID_FIRST_CONTACT_DATE',
  INVALID_LAST_CONTACT_DATE: 'INVALID_LAST_CONTACT_DATE',
  CONTACT_DATE_ORDER_INVALID: 'CONTACT_DATE_ORDER_INVALID',
  INVALID_CHANNEL: 'INVALID_CHANNEL',
  INVALID_BUYER_MESSAGE_COUNT: 'INVALID_BUYER_MESSAGE_COUNT',
  INVALID_OUR_MESSAGE_COUNT: 'INVALID_OUR_MESSAGE_COUNT',
  MISSING_LEAD_QUALITY: 'MISSING_LEAD_QUALITY',
  INVALID_LEAD_QUALITY: 'INVALID_LEAD_QUALITY',
  LEAD_QUALITY_REGRESSION: 'LEAD_QUALITY_REGRESSION',
  MISSING_OFFER_TYPE: 'MISSING_OFFER_TYPE',
  INVALID_OFFER_TYPE: 'INVALID_OFFER_TYPE',
  INVALID_INITIAL_CASH_OFFER: 'INVALID_INITIAL_CASH_OFFER',
  INVALID_BEST_CASH_OFFER: 'INVALID_BEST_CASH_OFFER',
  BEST_OFFER_LESS_THAN_INITIAL: 'BEST_OFFER_LESS_THAN_INITIAL',
  INVALID_CASH_COMPONENT: 'INVALID_CASH_COMPONENT',
  INVALID_TRADE_EST_VALUE: 'INVALID_TRADE_EST_VALUE',
  MISSING_STATUS: 'MISSING_STATUS',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_OUTCOME_REASON: 'INVALID_OUTCOME_REASON',
} as const;

// ── Row-level warning (non-fatal, does not force INVALID) ───────────────────
export const ROW_WARNING = {
  SOURCE_OLDER: 'SOURCE_OLDER',
} as const;
